### ISSUE TITLE
Customize the layout of the actions.

### ISSUE THREAD

**Issue by eymen-elkum** [cakemanager/cakephp-cakemanager#6]
In fact I am using the bootstrap-ui plugin, so I had this problem.
I want to use the default layout of the bootstrap-ui plugin witch is located in "TwitterBootstrap/default".
I did that by editing the function beforeFilter in UsersController.
`
        // Setting up the base-layout
        if (!$this->layout) {
            $this->layout = "TwitterBootstrap/default";
        }
`
but I wonder if there is another way to do that, or to add this fild to the configuration array.
like this:
`
        // Setting up the base-layout
        if (Configure::read('CM.baseLayout')) {
            $this->layout = !Configure::read('CM.baseLayout');
        }
        // Setting up the admin-layout
        if (Configure::read('CM.adminLayout')) {
            $this->layout = !Configure::read('CM.adminLayout');
        }
`

**Comment by bobmulder** [comment]
Hey @ayman-alkom,

I just implemented this feature for the CakeAdmin plugin (best practice of the CakeManager Plugin): http://cakemanager.org/docs/cakeadmin/1.0/general/configurations/#theming

Commit: https://github.com/cakemanager/cakephp-cakeadmin/commit/f6112cb3aa61338ff355852792ff60b6403f1444.

If you want to do this for the CakeManager, feel free to open a new Pull Request. Note that I won't update the CakeManager that much because the CakeAdmin plugin will replace the CakeManager and PostTypes plugin ;)

**Comment by eymen-elkum** [comment]
Ok @bobmulder 
Thanks a lot, I will migrate to CakeAdmin plugin.
